package net.mattemade.bigmode

const val WORLD_WIDTH = 320
const val WORLD_HEIGHT = 180
const val WORLD_WIDTH_FLOAT = WORLD_WIDTH.toFloat()
const val WORLD_HEIGHT_FLOAT = WORLD_HEIGHT.toFloat()

const val RESTAURANT_HEIGHT_RATIO = 2f
const val RESTAURANT_HEIGHT_REVERSE_RATIO = 1f / RESTAURANT_HEIGHT_RATIO
var RESTAURANT_WIDTH_RATIO = 1.2716715f
var MIN_RESTAURANT_WIDTH_RATIO = 0.75f
val MIN_RESTAURANT_WIDTH get() = WORLD_WIDTH * MIN_RESTAURANT_WIDTH_RATIO
val MAX_RESTAURANT_WIDTH get() = WORLD_WIDTH * RESTAURANT_WIDTH_RATIO
val RESTAURANT_WIDTH_DIFF = MAX_RESTAURANT_WIDTH - MIN_RESTAURANT_WIDTH
const val LEVELS = 5
val RESTAURANT_WIDTH_DIFF_PER_LEVEL get() = RESTAURANT_WIDTH_DIFF / LEVELS.toFloat()
var RESTAURANT_WIDTH = MIN_RESTAURANT_WIDTH// * RESTAURANT_WIDTH_RATIO
const val RESTAURANT_HEIGHT = WORLD_HEIGHT_FLOAT * RESTAURANT_HEIGHT_RATIO
const val FOOD_SECTION_TOP = 160f
const val FOOD_SECTION_BOTTOM = RESTAURANT_HEIGHT - 20f
const val RESTAURANT_TOP_BORDER = RESTAURANT_HEIGHT * 0.33f
const val HALF_WORLD_WIDTH_FLOAT = WORLD_WIDTH_FLOAT * 0.5f
const val HALF_WORLD_HEIGHT_FLOAT = WORLD_HEIGHT_FLOAT * 0.5f


const val TEXTURE_SCALE = 0.04f
const val BAND_SCALE = 0.035f
const val POWERUP_SCALE = 0.06f
const val BUTTON_SCALE = 0.125f
const val FROG_SCALE = 0.03f
const val SNAKE_SCALE = 0.04f
const val DONKEY_SCALE = 0.03f
const val DOG_SCALE = 0.03f
const val PLAYER_SCALE = 0.025f
const val HEART_SCALE = 0.04f
const val STAGE_TEXTURE_SCALE = 0.12f
var MUSIC_VOLUME = 0.1f
var CUTSCENE_MUSIC_VOLUME = 0.4f


const val CURTAINS_HEIGHT = WORLD_HEIGHT_FLOAT * 1.3f
const val CURTAINS_WIDTH = HALF_WORLD_WIDTH_FLOAT * 1.15f
const val RIGHT_CURTAIN_START = WORLD_WIDTH_FLOAT - CURTAINS_WIDTH